### ISSUE TITLE
Landing-Page: Low FPS on Chrome

### ISSUE THREAD

**Issue by ryyppy** [ReasonVienna/reason-conf-2019#15]
For some reasons I only get 20-30fps on scrolling down to the ticket section... I guess there's a lot of CSS layer composition going on

**Comment by okonet** [comment]
I fixed this today with #10. It didn't change perf on Chrome before nor after

**Comment by okonet** [comment]
![2018-10-01 at 18 15](https://user-images.githubusercontent.com/11071/46301202-f8d84980-c5a5-11e8-829c-f934fb4602b2.png)

**Comment by okonet** [comment]
Closable?

**Comment by okonet** [comment]
I've identified one more possible bottle-neck and going to PR a fix.
