### ISSUE TITLE
Add Terms of Service page

### ISSUE THREAD

**Issue by nikgraf** [ReasonVienna/reason-conf-2019#33]
## Refunds

You registration is non-refundable once purchased. Cancellations of your travel and/or hotel reservations are your own responsibility. Please notice, that if you can't attend for any reason you are responsible to cancel your room and flights.

## Transferring your Ticket

You can transfer your ticket until the day before the conference. Transferring you ticket once the conference has started is not allowed.

## Cancellation

The organisers can change the date of the event or cancel the event. If the event is cancelled any purchased ticket gets a full refund. If only a part e. g. a workshop is not taking place you get back the fee for the booked part, excluding the fee for the parts you still attend. Further claims against the organiser are not possible.

## Media

Our team will record videos and take photos at the event. It may happen that you will be included. With your registration you grant us the right to use such material taken over the days. Still everyone has the change during registration to inform our team that she or he doesn't like to be photographed. We will do our best to not take any pictures of you. Regardless if you informed our team about your preference in case you have concerns about any photo or video snippet that we published please let us know and we will remove it.

**Comment by okonet** [comment]
This is done in #42
