### ISSUE TITLE
Add cookies popup

### ISSUE THREAD

**Issue by okonet** [ReasonVienna/reason-conf-2019#44]
In order to integrate Google Analytics (#35) and comply to GDPR we need a cookies confirmation from users.

Example

![2018-10-19 at 09 56](https://user-images.githubusercontent.com/11071/47205139-63023400-d385-11e8-9038-8964ab46c1b3.png)

**Comment by ryyppy** [comment]
I've found out how to get interactive components integrated.. should I create a PR demonstrating this?

**Comment by okonet** [comment]
Yes please!

**Comment by cezarneaga** [comment]
first lets see how complex this should be :)

will there be login with google, twitter, fb?
will there be fb pixel?
will there be just GA for analytics?
will there be google ads? (i hope not)

do we need customizable settings? or just an on/off.

we need a cookie policy page or at least a section in privacy policy.

**Comment by okonet** [comment]
Copy ideas:

```
We use cookies and other tracking technologies to improve your browsing experience on our site, show personalized content and targeted ads, analyze site traffic, and understand where our audience is coming from. To find out more or to opt-out, please read our Cookie Policy. In addition, please read our Privacy Policy, which has also been updated and became effective May 23rd, 2018.

By choosing I Accept, you consent to our use of cookies and other tracking technologies.
```

**Comment by okonet** [comment]
I'm not sure what "Decline" action should perform. @cezarneaga probably you could advise? Looks like right now it just hides it and deletes the cookie. If this is the case, then we'll have to disable GA? How are we going to do that?

**Comment by okonet** [comment]
@ryyppy I updated design. Please review and merge.

**Comment by cezarneaga** [comment]
> I'm not sure what "Decline" action should perform. @cezarneaga probably you could advise? Looks like right now it just hides it and deletes the cookie. If this is the case, then we'll have to disable GA? How are we going to do that?

the GA code needs to be wrapped in a conditional:

```
if (document.cookie.indexOf('gdpr-cookie=1') >= 0){
  GA(....)
}
```

**Comment by okonet** [comment]
Thanks @cezarneaga

**Comment by nikgraf** [comment]
Will be closed with this PR https://github.com/ReasonVienna/reason-conf-2019/pull/54
